# Generated by Django 3.0.4 on 2020-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_manager_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.ImageField(null=True, upload_to='user_resumes'),
        ),
    ]
