# Generated by Django 3.0.4 on 2020-04-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.TextField(default=''),
        ),
    ]
