# Generated by Django 3.0.4 on 2020-04-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200418_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numFollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='numFollowing',
            field=models.IntegerField(default=0),
        ),
    ]
