# Generated by Django 3.0.4 on 2020-04-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200418_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='numFollowers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='numFollowing',
        ),
    ]
