# Generated by Django 3.0.5 on 2020-04-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200418_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.TextField(default='^'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.TextField(default='^'),
        ),
    ]
